# Generated by Django 4.2.24 on 2025-09-18 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=29, unique=True)),
                ('plan', models.CharField(default='pro', max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_devices', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('token_version', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('first_activated_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked', models.BooleanField(default=False)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.licensekey')),
            ],
            options={
                'unique_together': {('license_key', 'device_id')},
            },
        ),
    ]
