# Generated by Django 4.2.24 on 2025-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
